// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: login.sql

package sqlc

import (
	"context"
)

const selectAccountByEmailHash = `-- name: SelectAccountByEmailHash :one
SELECT id
FROM users
WHERE email = $1
AND password = $2
`

type SelectAccountByEmailHashParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) SelectAccountByEmailHash(ctx context.Context, arg SelectAccountByEmailHashParams) (int32, error) {
	row := q.db.QueryRow(ctx, selectAccountByEmailHash, arg.Email, arg.PasswordHash)
	var id int32
	err := row.Scan(&id)
	return id, err
}
