// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: notifications.sql

package sqlc

import (
	"context"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (event_type, flight_number)
VALUES ($1, $2)
RETURNING id
`

type CreateNotificationParams struct {
	EventType    string `json:"event_type"`
	FlightNumber string `json:"flight_number"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (int32, error) {
	row := q.db.QueryRow(ctx, createNotification, arg.EventType, arg.FlightNumber)
	var id int32
	err := row.Scan(&id)
	return id, err
}
