// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: notifications.sql

package sqlc

type CreateNotificationsParams struct {
	User    int32  `json:"user"`
	Title   string `json:"title"`
	Message string `json:"message"`
}
